export const products = [
  {
    _id: 1,
    name: "Black Shirt",
    Description: "Crafted from a premium blend of 74% Lyocell, 19% Nylon, and 7% Polyester, this slim-fit shirt features a sleek black base with white stripes. Its full sleeves and classic collar make it a versatile addition to any wardrobe, offering both style and comfort for any occasion.",
    Rating: 4.5,
    currentprice: 19.99,
    image: "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4MSS4057-05_1_d6e7a340-408b-4486-b0e6-71160d492c69.jpg?v=1744140420&quality=20",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Men",
    subCategory:"Shirt",
    offer:"",
  },
  {
    _id: 2,
    name: "Dark Blue, White, Black Top",
    Description: "Casual Regular Sleeves Printed Women Dark Blue, White, Black Top",
    Rating: 4.8,
    currentprice: 59.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/i/y/s/xxl-1047-short-kurta-mahfil-original-imah5ffvzqjjgsce.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Kurta",
    offer:40,
  },
  {
    _id: 3,
    name: "Boys & Girls  T Shirt",
    Description: "Boys & Girls Printed Cotton Blend Regular T Shirt",
    Rating: 4.6,
    currentprice: 129.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/s/r/n/8-9-years-neuvo-73-rudra-original-imah5g9ynajv8kdz.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Kid",
    subCategory:"Shirt",
    offer:"",
  },
  {
    _id: 4,
    name: "Blue Jeans",
    Description: "Women Relaxed Fit Mid Rise Blue Jeans.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/h/y/t/36-wl-stone-blue1-zayla-original-imahf4p2zhwkb9hq.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Jean",
    offer:"",
  },
 
  {
    _id: 5,
    name: "Yellow Blend Slim Fit Shirt",
    Description: "Give a majestic lift to your look with this yellow plain pattern shirt. The shirt is crafted from fine 70% cotton 30% linen. It is a versatile staple and great for teaming with jeans for a more casual look or smartening up with a classic pair of chinos.",
    Rating: 4.3,
    currentprice: 29.99,
    image: "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4MSS3977-08_1_51b68849-8521-4a12-a778-51b3050d9d6f.jpg?v=1741767823&quality=20",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Men",
    subCategory:"Shirt",
    offer:"",
  },
  {
    _id: 6,
    name: "Pure Cotton Purple T-Shirt",
    Description: "Women Printed Round Neck Pure Cotton Purple T-Shirt",
    Rating: 4.7,
    currentprice: 89.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/q/a/h/xl-10968510-roadster-original-imafpmh52juzesev-bb.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Shirt",
    offer:40,
  },
  {
    _id: 7,
    name: "Boys Printed  T Shirt",
    Description: "Boys Printed Cotton Blend Regular T Shirt",
    Rating: 4.1,
    currentprice: 34.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/q/t/y/8-9-years-neuvo-257-rudra-original-imah5gkmzvcetz7a.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Kid",
    subCategory:"Shirt",
    offer:"",
  },
  {
    _id: 8,
    name: "Blue Jeans",
    Description: "Women Relaxed Fit Mid Rise Blue Jeans.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/u/e/k/xxl-hft-24hds-be3-hellcat-original-imagzv2bsahgpze5.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Kurta",
    offer:"",
  },
 
  {
    _id: 9,
    name: "Dark Blue Slim Fit Shirt",
    Description: "Give your everyday wardrobe an effortless appeal with this classy dark blue 98% polyester, 2% spandex shirt. Designed in a slim fit, this shirt is known for its endless versatility. A look that bridges dressy and casual, with full sleeve and spread, it is perfect to wear alone or as an outer layer.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4MSS3888-01_1_2cb04f8b-2338-4d64-9d8e-a9cff4ef4473.jpg?v=1743502412&quality=20",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Men",
    subCategory:"Shirt",
    offer:"",
  },
  {
    _id: 10,
    name: "Black Woven Mandarin Shirt",
    Description: "Update your everyday shirt collection with this cool and comfy slim fit full sleeve shirt from snitch. The slim fit lends you an easygoing look and with our breathable shirts in 100% cotton, comfort is no longer reserved for the weekends.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/dea8a00ccacd17d2a9ff4a315c116b42.webp?v=1724415283&quality=20",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Men",
    subCategory:"Shirt",
    offer:"",
  },
  {
    _id: 11,
    name: "Women Casual Shirt",
    Description: "Women Regular Fit Embroidered Mandarin Collar Casual Shirt",
    Rating: 4.0,
    currentprice: 24.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/e/v/s/m-67iqtp-iqraar-original-imahaz35gdavv4yc.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Shirt",
    offer:40,
  },
  {
    _id: 12,
    name: "Black Stripes Slim Fit Shirt",
    Description: "Maintain a timeless look as you transition between smart and casual in timeless style with snitch's new season collection of men's shirts. No matter what your style is, you need this full sleeve slim fit shirt in your wardrobe. It is made from 100% cotton and features a roomy cut for a casual style.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/6e8da19be6c6598aa4be83f2e0d6fc63.jpg?v=1734527839&quality=20",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Men",
    subCategory:"Shirt",
    offer:"",
  },
 
  {
    _id: 13,
    name: "Silk Blend Saree ",
    Description: "Woven, Embellished Banarasi Silk Blend Saree  (Multicolor, Grey)",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/9/m/t/free-sky7101-superlaxmi-unstitched-original-imah9r55zqtkyate.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Saree",
    offer:"",
  },
  {
    _id: 14,
    name: "Light Grey Shirt",
    Description: "Update your everyday shirt collection with this cool and comfy slim fit full sleeve shirt from snitch. The slim fit lends you an easygoing look and with our breathable shirts in 72.4% viscose, 20.2% nylon, 7.4% linen, comfort is no longer reserved for the weekends.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4MSS3839-03_1_d490024d-6a4c-4cf2-8c03-d781f21a6cf8.jpg?v=1739287035&quality=20",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Men",
    subCategory:"Shirt",
    offer:"",
  },
  {
    _id: 15,
    name: "Viscose Rayon Kurta",
    Description: "Featuring an elegant self-design pattern, this women’s kurta and sharara set stands out with its subtle charm. The intricate embroidery on the kurta adds a refined touch, while the gotta patti work on the sharara pants elevates the overall design. Thus, this set combines traditional craftsmanship with modern elegance, making it a standout choice for various occasions.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/ethnic-set/r/m/e/m-jef-rbd-814-jaffry-embroidery-original-imah8ag3agbm2hgq.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Kurta",
    offer:"",
  },
  {
    _id: 16,
    name: "Silk Saree",
    Description: "Update your everyday shirt collection with this cool and comfy slim fit full sleeve shirt from snitch. The slim fit lends you an easygoing look and with our breathable shirts in 72.4% viscose, 20.2% nylon, 7.4% linen, comfort is no longer reserved for the weekends.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/3/j/p/free-turky-box-pink-house-house-of-common-unstitched-original-imah3zye2uvh3dhr.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Saree",
    offer:40,
  },
  {
    _id: 17,
    name: "Blue Jeans",
    Description: "Women Regular High Rise Blue Jeans",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/o/1/u/28-kttladiesjeans854-kotty-original-imags7tess6zjqjx.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Jean",
    offer:"",
  },
  {
    _id: 18,
    name: "Jacquard Silk Saree",
    Description: "Self Design Kanjivaram Jacquard, Art Silk Saree  (Blue)",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/6/b/i/free-kp-6010-ritcher-unstitched-original-imah7dfjsn8g4gvz.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Saree",
    offer:"",
  },

  {
    _id: 19,
    name: " Blue Jeans",
    Description: "Women Flared High Rise Blue Jeans.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/m/1/d/36-11542062-roadster-original-imagfvzcwfy6cdwg-bb.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Jean",
    offer:"",
  },
  {
    _id: 4,
    name: "Mauve Block Checks Shirt",
    Description: "Elevate your wardrobe with this Slim Fit shirt from Snitch, featuring a unique check pattern in a rich mauve shade. Crafted from 100% polyester, it offers a smooth texture and a modern spread collar. Perfect for both casual and formal settings, this shirt combines style and comfort effortlessly.",
    Rating: 4.2,
    currentprice: 74.99,
    image: "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4mss3847-06_5_f9150e3a-aa6d-49f8-8e1c-afb9e31e506f.jpg?v=1739423173&quality=20",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Men",
    subCategory:"Shirt",
    offer:"",
  },
  {
    _id: 21,
    name: "Bollywood Chiffon Saree",
    Description: "Embellished Bollywood Chiffon Saree  (Dark Green)",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/m/r/x/free-rama-saree-kakadiya-creation-unstitched-original-imahf3p8hhrvrwfw.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Saree",
    offer:"40",
  },
  {
    _id: 22,
    name: "Dark Blue Checks Shirt",
    Description: "Give a majestic lift to your look with this black stripes pattern shirt. The shirt is crafted from fine 100% cotton. It is a versatile staple and great for teaming with jeans for a more casual look or smartening up with a classic pair of chinos.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/ca54778b8e7dbc9a728bac6b3b2a948e.jpg?v=1734529148&quality=20",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Men",
    subCategory:"Shirt",
    offer:"",
  },
  {
    _id: 23,
    name: "Kanjivaram Silk Saree",
    Description: "Woven, Temple Border Kanjivaram Pure Silk, Art Silk Saree  (Blue)",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/w/z/l/free-4241s6684-samah-unstitched-original-imahadwy35thr7pw.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Saree",
    offer:"",
  },
  {
    _id: 24,
    name: "Georgette Saree ",
    Description: "Embellished Bollywood Georgette Saree  (Purple)",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/s/w/y/free-2-star-sheldrom-mart-unstitched-original-imahb3gsmqurhyes.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Saree",
    offer:"",
  },
 
  {
    _id: 26,
    name: "Spread Collar Casual Shirt",
    Description: "Boys Regular Fit Washed Spread Collar Casual Shirt.",
    Rating: 4.4,
    currentprice: 49.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/x/c/9/13-14-years-cz-24-kds-db-fs-cazzba-original-imagyhx2ezygcfzg.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Kid",
    subCategory:"Shirt",
    offer:"",
  },
  {
    _id: 25,
    name: " Black Jeans",
    Description: "Featuring a timeless solid pattern, these women’s jeans offer an ideal blend of sophistication and style. Plus, thanks to their clean look, they exude elegance, offering a polished look for any occasion. Thus, you can effortlessly transition from a casual day out to a chic evening event, thanks to these versatile jeans.",
    Rating: 4.5,
    currentprice: 39.99,
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/y/r/w/38-highwaist010-tyffyn-original-imah3g9vsjy5pw6f.jpeg?q=70",
    Sizes: ["S", "M", "L", "XL", "XXL"],
    Category: "Women",
    subCategory:"Jean",
    offer:"",
  },
  
];







// export const products=[
//         {
//             "_id": "6846990ec3b36db0ed0c5ca5",
//             "name": "tomato",
//             "description": "fresh torange tomato for healthy life",
//             "discount": 20,
//             "originalprice": 50,
//             "currentprice": 30,
//             "ratings": 0,
//             "image": [
//                 {
//                     "public_id": "products/z5si98klnuokor6woqo3",
//                     "url": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4MSS3977-08_1_51b68849-8521-4a12-a778-51b3050d9d6f.jpg?v=1741767823&quality=20",
//                     "_id": "6846990ec3b36db0ed0c5ca6"
//                 },
//                 {
//                     "public_id": "products/ykfmn03qyfbxrhmxjc2x",
//                     "url": "https://res.cloudinary.com/dbzcmxy5f/image/upload/v1749457165/products/ykfmn03qyfbxrhmxjc2x.png",
//                     "_id": "6846990ec3b36db0ed0c5ca7"
//                 }
//             ],
//             "category": "vegetable",
//             "stock": 1,
//             "numOfReviews": 0,
//             "user": "68457a0ef1844165f6573529",
//             "reviews": [
//                {
//                 "user": "68457a0ef1844165f6573529",
//                 "name": "hshshs",
//                 "rating": 1,
//                 "comment": "this is good product",
//                 "_id": "6846f3d5c3b36db0ed0c5cc9"
//             },
//               {
//                 "user": "68457a0ef1844165f6573529",
//                 "name": "hshshs",
//                 "rating": 1,
//                 "comment": "wonderfull product",
//                 "_id": "6846f3d5c3b36db0ed0c5cc9"
//             }
//             ],
//             "createdAt": "2025-06-09T08:19:26.006Z",
//             "__v": 0
//         },
//         {
//             "_id": "68469944c3b36db0ed0c5caa",
//             "name": "patoto",
//             "description": "fresh  patato for healthy life",
//             "discount": 10,
//             "originalprice": 50,
//             "currentprice": 40,
//             "ratings": 0,
//             "image": [
//             {
//                 "public_id": "products/zhiysjtfpyaypavgew0a",
//                 "url": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4MSS3977-08_1_51b68849-8521-4a12-a778-51b3050d9d6f.jpg?v=1741767823&quality=20",
//                 "_id": "68471220c3b36db0ed0c5cd6"
//             },
//             {
//                 "public_id": "products/g1omvx5vfi9xtpaxo6lj",
//                 "url": "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/h/y/t/36-wl-stone-blue1-zayla-original-imahf4p2zhwkb9hq.jpeg?q=70",
//                 "_id": "68471220c3b36db0ed0c5cd7"
//             },
//             {
//                 "public_id": "products/z2jmnegeolm1isi6ycuh",
//                 "url": "https://res.cloudinary.com/dbzcmxy5f/image/upload/v1749488160/products/z2jmnegeolm1isi6ycuh.png",
//                 "_id": "68471220c3b36db0ed0c5cd8"
//             },
//             {
//                 "public_id": "products/kfiows6cnfyruiihrjlo",
//                 "url": "https://res.cloudinary.com/dbzcmxy5f/image/upload/v1749488162/products/kfiows6cnfyruiihrjlo.png",
//                 "_id": "68471220c3b36db0ed0c5cd9"
//             }
//         ],
//             "category": "vegetable",
//             "stock": 1,
//             "numOfReviews": 0,
//             "user": "68457a0ef1844165f6573529",
//             "reviews": [
              
//                  {
//                 "user": "68457a0ef1844165f6573529",
//                 "name": "hshshs",
//                 "rating": 3,
//                 "comment": "this is good product",
//                 "_id": "6846f3d5c3b36db0ed0c5cc9"
            
//                  },
//                    {
//                 "user": "68457a0ef1844165f6573529",
//                 "name": "hshshs",
//                 "rating": 4,
//                 "comment": "wonderfull product",
//                 "_id": "6846f3d5c3b36db0ed0c5cc9"
//             }
//             ],
//             "createdAt": "2025-06-09T08:20:20.738Z",
//             "__v": 0
//         },
//         {
//             "_id": "68469970c3b36db0ed0c5caf",
//             "name": "apple",
//             "description": "fresh  apple for healthy life",
//             "discount": 10,
//             "originalprice": 100,
//             "currentprice": 90,
//             "ratings": 0,
//             "image": [
//                 {
//                     "public_id": "products/wnhimpl3xglcxhklm9yj",
//                     "url": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4MSS4057-05_1_d6e7a340-408b-4486-b0e6-71160d492c69.jpg?v=1744140420&quality=20",
//                     "_id": "68469970c3b36db0ed0c5cb0"
//                 },
//                 {
//                     "public_id": "products/rijw6kqwz0oxeg6uavwi",
//                     "url": "https://res.cloudinary.com/dbzcmxy5f/image/upload/v1749457263/products/rijw6kqwz0oxeg6uavwi.png",
//                     "_id": "68469970c3b36db0ed0c5cb1"
//                 }
//             ],
//             "category": "fruit",
//             "stock": 1,
//             "numOfReviews": 0,
//             "user": "68457a0ef1844165f6573529",
//             "reviews": [
//                {
//                 "user": "68457a0ef1844165f6573529",
//                 "name": "hshshs",
//                 "rating": 2,
//                 "comment": "this is good product",
//                 "_id": "6846f3d5c3b36db0ed0c5cc9"
//             },
//               {
//                 "user": "68457a0ef1844165f6573529",
//                 "name": "hshshs",
//                 "rating": 3,
//                 "comment": "wonderfull product",
//                 "_id": "6846f3d5c3b36db0ed0c5cc9"
//             },
//               {
//                 "user": "68457a0ef1844165f6573529",
//                 "name": "hshshs",
//                 "rating": 3,
//                 "comment": "wonderfull product",
//                 "_id": "6846f3d5c3b36db0ed0c5cc9"
//             }
//             ],
//             "createdAt": "2025-06-09T08:21:04.105Z",
//             "__v": 0
//         }
//     ]